### ISSUE TITLE
Details of the json files 

### ISSUE THREAD

**Issue by d4x1** [melianmiko/mibandpreview#1]
I like this project. 
After reading the codes. I find this program parse a json file and preview it.
I want to know more about the details of the json file (that stands for a watchface) 
including how to get the json file ? and how many fields in it? and how to convert json file to a bin file.

Can you help me ?

**Comment by melianmiko** [comment]
Sorry for not answering, I didn't receive a notification about this issue.

You can use this tool to unpack and pack back Mi Band 4-6 watchfaces: https://amazfitwatchfaces.com/forum/viewtopic.php?t=720&sid=992b89e40cbd9db659a5137c42c36861
Also you can create a JSON manually, but I don't have structure guide, for now.

**Comment by d4x1** [comment]
@melianmiko thanks.
