### ISSUE TITLE
StatusSimplified missing

### ISSUE THREAD

**Issue by diopter12** [melianmiko/mibandpreview#2]
StatusSimplified is not viewed.
I think your goal is an EXACT preview,
but sometimes pixels on the edges are visible in your (and others) preview,
but not on the real MI band 6.

Please add input fields for:
Alarm time
Alarm on (check box)
Alarm no time (check box)
TimeZone1 time (sunset)
TimeZone2 time (sunrise)
No time zone (check box)
km/Mi

Your preview image file is very good (small file size),
please create a small (110x352) image file too.

**Comment by melianmiko** [comment]
> Alarm on (check box)

Already exists, check hat you're using latest version (1.0)

> Alarm no time (check box)

Isn't this the same as "Alarm on"?

> StatusSimplified is not viewed.

Can you please give an example watchface with this element?

**Comment by diopter12** [comment]
Alarm on (check box): OK, sorry
Alarm no time (check box): it's for "ImageNoAlarm" in the json.
https://amazfitwatchfaces.com/mi-band-6/view/3439
https://amazfitwatchfaces.com/mi-band-5/view/450
I have updated my issue, see first posting.

Thanks for your fast answer.

**Comment by diopter12** [comment]
Alarm on (check box): OK, sorry
Alarm no time (check box): it's for "ImageNoAlarm" in the json.
https://amazfitwatchfaces.com/mi-band-6/view/3439
https://amazfitwatchfaces.com/mi-band-5/view/450
I have updated my issue, see first posting.

Thanks for your fast answer.

2022-04-01 12:34 GMT+02:00, MelianMiko ***@***.***>:

**Comment by melianmiko** [comment]
> Alarm no time (check box): it's for "ImageNoAlarm" in the json.

When "Alarm On" is unchecked, this image will also be displayed.

**Comment by melianmiko** [comment]
Added inputs: Timezone (time + disable checkbox), Alarm Time, Distance unit.
Added basic StatusSimplified support.

Will be available since version 1.1 release.
