### ISSUE TITLE
Positioning does not match real MI Band 6

### ISSUE THREAD

**Issue by diopter12** [melianmiko/mibandpreview#6]
Maybe your positioning of the elements is correct, but it does not match with the positioning on the real MI Band 6.
If elements on real MI Band 6 are already cut off at the outer edges, they are still completely visible on your preview (1 pixel more, I think).
I suspect a firmware bug in the MI Band 6, of which there are quite a few ...

**Comment by melianmiko** [comment]
I can't fix it, at least becouse I don't have Mi Band 6 =)

Edges of preview are trimmed via this mask: https://github.com/melianmiko/mibandpreview/blob/main/mibandpreview/res/mb6_mask.png
White pixels of this mask are visible, other don't. If you want, you can manually fix them or create another and provide it to me. You can find/replace them in already installed application, it's located in `C:\Program Files\MelianMiko\Mi Band Preview\mibandpreview\res` folder (Windows).

**Comment by diopter12** [comment]
The clipping mask should not use antialiasing, the real MI Band 6 does not do that at the screen edges either.
https://user-images.githubusercontent.com/102797829/161415790-d5319b08-ca3f-4dd3-8b48-3067168ee924.png
.

**Comment by diopter12** [comment]
This should be better:
https://user-images.githubusercontent.com/102797829/161422684-70e2d18c-da82-4033-b32d-22ec3c5a76cd.png

The best way may be, first use my mask for clipping and then use your mask for antialiasing.

**Comment by melianmiko** [comment]
Let the user choose will be easier =)

![image](https://user-images.githubusercontent.com/67851274/161467310-7cb2ba8d-4333-40da-9b13-cc758ba6f3e7.png)
