### ISSUE TITLE
Time: TimeDelimiterImage not shown

### ISSUE THREAD

**Issue by diopter12** [melianmiko/mibandpreview#9]
Time: DelimiterImage works

**Comment by melianmiko** [comment]
Give an example watchface please...

**Comment by diopter12** [comment]
I have no example watchface, but TimeDelimiterImage is exactly the same as DelimiterImage.
It's for use between minutes and seconds, but seconds are not working because of firmware bugs.
I use it to display an image somewhere on the watch face, so there must not be a full size background image.

**Comment by melianmiko** [comment]
Will be available in v1.2
